#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/m3ter-com/m3ter-sdk-go,github.com/stainless-sdks/m3ter-sdk-go"

go build -o terraform-provider-m3ter
