#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ -n "$1" ]]; then
  LOCAL_GO="$1"
  shift
else
  LOCAL_GO=../m3ter-go
fi

echo "==> Linking with local directory"
go mod tidy -e
go mod edit -replace github.com/m3ter-com/m3ter-sdk-go="$LOCAL_GO"
