#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/m3ter-com/m3ter-sdk-go,github.com/stainless-sdks/m3ter-sdk-go"

REPLACEMENT="${1:-"../m3ter-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/m3ter-com/m3ter-sdk-go="$REPLACEMENT"
go mod tidy -e
